language: python
python: "3.7"

matrix:
  include:
    # clang-tidy/format specific job
    - os: linux
      sudo: false
      env: CLANG_FORMAT CLANG_TIDY
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'clang', 'clang-format', 'clang-tidy', 'libstdc++-8-dev' ]
      script:
        - make tidy
        - make format
    - os: linux
      sudo: false
      env: CXX=g++-9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-9' ]
    - os: linux
      sudo: false
      env: CXX=clang++
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'clang', 'libstdc++-8-dev' ]
    - os: linux
      sudo: required # workaround https://github.com/mapbox/node-cpp-skel/issues/93
      env: CXXFLAGS="-fsanitize=address,undefined -fno-sanitize-recover=all"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'clang', 'libstdc++-8-dev' ]
    # coverage build
    - os: linux
      sudo: false
      env: CXXFLAGS="--coverage" LDFLAGS="--coverage"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'clang', 'llvm', 'libstdc++-8-dev' ]
      script:
        - make debug
        - make test
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        - ./codecov -x "llvm-cov gcov -l" -Z

env:
  global:
   - CMAKE_VERSION="3.15.2"

install:
  - pip install conan
  - which cmake

script:
  - make release
  - make test
  - make clean
  - make debug
  - make test
  - make clean
