load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "kdtreepp",
    hdrs = glob(["include/**/*.hpp"]),
    strip_include_prefix = "include",
    deps = ["@eigen//:eigen"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "regression_test",
    srcs = ["test/regression.cpp"],
    deps = [":kdtreepp"],
)
